######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 5 12:55:49 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h
SOURCES += main.cpp MainWindow.cpp
